name: Run Parser
on:
  workflow_dispatch:

concurrency:
  group: run
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  discover:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: astral-sh/setup-uv@v5 # but hey we use the nix version anyways...

      - run: |
          cat << EOF > script.sh
          set -euo pipefail
          railgo-mongod &
          uv run main.py
          EOF
          nix develop --command bash script.sh

      - uses: actions/upload-artifact@v4
        with:
          name: RailGo
          path: export/railgo.sqlite
